### ISSUE TITLE
Similar library

### ISSUE THREAD

**Issue by jpillora** [tj/go-config#6]
Hey @tj I wrote a similar library a while back https://github.com/jpillora/opts (stole many ideas from [commanderjs](https://github.com/tj/commander.js) ;) ) though haven't announced it yet because I haven't fully fleshed out sub-commands. I've also added a templating system to customize the `--help` screen. Thoughts?

**Comment by tj** [comment]
ah darn, hard to find things sometimes, I was searching for 'struct config'. help is much nicer than desc haha, stealin that. For anything that needs arguments or sub commands I generally use docopt, it's really flexible at expression the more complex programs, but I like the simplicity of structs for the average use-case. I'd still like to tweak docopt some day to accept a struct and use that for coercion

**Comment by jpillora** [comment]
docopt looked pretty cool, though I'm not a huge fan of map[string]
interface{} so I rolled my own and went with structs. I think I've got help
text API down, I just need to redo sub commands. Also will rewrite the
README, will try to make it more user and SEO friendly :+1:
